# File: .github/workflows/repo-sync.yml
name: tubie
on:
  schedule:
    - cron: '20 14 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: tubie
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 开始自动同步
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/tubie75/jdqd.git"
          source_branch: "main"
          destination_branch: "dust"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
